# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import nltkapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('internal_nltk_name', models.CharField(blank=True, help_text='Leave blank unless you are adding an NLTK built-in corpus, in which case, supply the name of the corpus.', max_length=15, verbose_name='Internal NLTK Corpus name (optional)')),
                ('internal_nltk_filter', models.CharField(blank=True, help_text='Used with Internal NLTK Corpus name if you want to filter the NLTK Corpus even further. Leave blank for default.', max_length=30, verbose_name='Internal NLTK Corpus filter (optional)')),
            ],
            options={
                'verbose_name_plural': 'Corpora',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=nltkapp.models.document_file_location)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nltkapp.Corpus')),
            ],
        ),
    ]
